# Generated by Django 3.1.1 on 2021-02-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
