# Generated by Django 3.1.1 on 2021-02-17 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0004_baby_items_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='baby_todo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='housemanager.todo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogs',
            name='dog_todo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='housemanager.todo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housemanager.items')),
                ('house_todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housemanager.todo')),
            ],
        ),
    ]
