# Generated by Django 3.1.1 on 2021-02-17 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0005_auto_20210217_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='baby_names',
        ),
        migrations.AddField(
            model_name='baby',
            name='baby_items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='housemanager.items'),
            preserve_default=False,
        ),
    ]
