# Generated by Django 3.1.1 on 2021-02-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0006_auto_20210217_1203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
    ]
