# Generated by Django 3.1.1 on 2021-02-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0008_todo_todo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='baby_items',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='baby_todo',
        ),
        migrations.RemoveField(
            model_name='dogs',
            name='dog_todo',
        ),
        migrations.AddField(
            model_name='baby',
            name='baby_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='baby_items',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='housemanager.baby'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='dog_items',
            field=models.ManyToManyField(related_name='Dog_items', to='housemanager.Dogs'),
        ),
        migrations.AddField(
            model_name='todo',
            name='baby_todo',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='housemanager.baby'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='dogs_todo',
            field=models.ManyToManyField(related_name='Dogs_todo', to='housemanager.Dogs'),
        ),
    ]
