# Generated by Django 3.1.1 on 2021-02-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0010_auto_20210217_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='dog_items',
            field=models.ManyToManyField(blank=True, related_name='Dog_items', to='housemanager.Dogs'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='baby_todo',
            field=models.ManyToManyField(blank=True, related_name='Baby_todo', to='housemanager.Baby'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='dogs_todo',
            field=models.ManyToManyField(blank=True, related_name='Dogs_todo', to='housemanager.Dogs'),
        ),
    ]
