# Generated by Django 3.1.1 on 2021-02-18 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0011_auto_20210217_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(max_length=200)),
                ('bill_photo', models.ImageField(upload_to='')),
                ('bill_due', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(max_length=200)),
                ('vaccine_lastdate', models.DateTimeField()),
                ('vaccine_duedate', models.DateTimeField()),
                ('vaccine_dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housemanager.dogs')),
            ],
        ),
    ]
