# Generated by Django 3.1.1 on 2021-03-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0016_auto_20210314_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='bill_photo',
        ),
        migrations.AddField(
            model_name='bills',
            name='bill_amount',
            field=models.IntegerField(default=0),
        ),
    ]
