# Generated by Django 3.1.1 on 2021-03-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0017_auto_20210316_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='baby_note',
            field=models.TextField(blank=True),
        ),
    ]
