# Generated by Django 3.1.1 on 2021-03-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0018_baby_baby_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='baby_name',
            field=models.CharField(default='Iora', max_length=100),
        ),
    ]
