# Generated by Django 3.1.1 on 2021-03-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0020_vaccine_v_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='baby_note',
        ),
    ]
