# Generated by Django 3.1.1 on 2021-03-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0021_remove_baby_baby_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
