# Generated by Django 3.1.1 on 2021-03-23 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0025_baby_baby_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='baby_due',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
