# Generated by Django 3.1.1 on 2021-03-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0026_auto_20210323_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='baby_name',
            field=models.CharField(max_length=100),
        ),
    ]
