# Generated by Django 3.1.1 on 2021-03-23 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemanager', '0027_auto_20210323_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='baby_due',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
